# Generated by Django 2.0.5 on 2018-05-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=50)),
                ('colour', models.IntegerField()),
                ('alcohol_percentage', models.FloatField()),
                ('body', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_option_name', models.CharField(max_length=20)),
                ('beer', models.ManyToManyField(to='home.Beer')),
            ],
        ),
        migrations.CreateModel(
            name='TasteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_option_name', models.CharField(max_length=50)),
                ('beer', models.ManyToManyField(to='home.Beer')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Brand'),
        ),
    ]
