# Generated by Django 2.0.5 on 2018-06-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='bottlePrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beer',
            name='canPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beer',
            name='kegPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
