# Generated by Django 2.0.5 on 2018-05-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='body_type',
        ),
        migrations.AddField(
            model_name='bodytype',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Beer'),
        ),
        migrations.RemoveField(
            model_name='containerstyle',
            name='beer',
        ),
        migrations.AddField(
            model_name='containerstyle',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Beer'),
        ),
        migrations.RemoveField(
            model_name='taste',
            name='beer',
        ),
        migrations.AddField(
            model_name='taste',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Beer'),
        ),
    ]
