# Generated by Django 2.0.5 on 2018-05-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingValue',
            field=models.IntegerField(default=0),
        ),
    ]
