# Generated by Django 2.0.5 on 2018-05-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_option_name', models.CharField(max_length=20)),
                ('beer', models.ManyToManyField(to='home.Beer')),
            ],
        ),
        migrations.CreateModel(
            name='TasteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_option_name', models.CharField(max_length=50)),
                ('beer', models.ManyToManyField(to='home.Beer')),
            ],
        ),
        migrations.RemoveField(
            model_name='containeroptions',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='tasteoptions',
            name='beer',
        ),
        migrations.DeleteModel(
            name='ContainerOptions',
        ),
        migrations.DeleteModel(
            name='TasteOptions',
        ),
    ]
