# Generated by Django 2.0.5 on 2018-05-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180526_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeroption',
            name='beer',
            field=models.ManyToManyField(blank=True, to='home.Beer'),
        ),
        migrations.AlterField(
            model_name='tasteoption',
            name='beer',
            field=models.ManyToManyField(blank=True, to='home.Beer'),
        ),
    ]
