# Generated by Django 2.0.5 on 2018-06-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180606_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='bottlePrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='canPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='kegPrice',
            field=models.FloatField(null=True),
        ),
    ]
