# Generated by Django 2.0.5 on 2018-05-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180527_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='alcohol_percentage',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='colour',
        ),
        migrations.AddField(
            model_name='beer',
            name='alcohol_by_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beer',
            name='colour_srm_value',
            field=models.FloatField(default=0.0),
        ),
    ]
