# Generated by Django 2.0.5 on 2018-06-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180606_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='canPrice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
