# Generated by Django 2.0.5 on 2018-05-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180527_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='body',
        ),
    ]
