# Generated by Django 2.0.5 on 2018-07-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180606_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='colourValue',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='raterName',
        ),
        migrations.AddField(
            model_name='beer',
            name='colourHex',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
