# Generated by Django 2.0.5 on 2018-07-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180713_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='colourHex',
        ),
        migrations.AddField(
            model_name='beer',
            name='beerPhoto',
            field=models.ImageField(blank=True, upload_to='home/media/beers/'),
        ),
    ]
