# Generated by Django 2.0.5 on 2018-07-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180721_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colourNum', models.IntegerField(default=0)),
                ('colourHex', models.CharField(max_length=10)),
            ],
        ),
    ]
