# Generated by Django 2.0.5 on 2018-07-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180719_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='colour',
        ),
        migrations.AddField(
            model_name='beer',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Colour'),
        ),
    ]
