# Generated by Django 2.0.5 on 2018-07-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_colour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.AlterField(
            model_name='beer',
            name='beerPhoto',
            field=models.ImageField(blank=True, upload_to='beers'),
        ),
    ]
